# -*- coding: utf-8 -*-
"""RAG on doctor dataset using mistral 7B instruct model (HF)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-W01H7yndSvaaiATWztNvCghoysXHok

#RAG application using Langchain and Llama 3

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
"""

!pip install langchain==0.1.17 langchain-community transformers datasets sentence-transformers faiss-cpu

from langchain.document_loaders import HuggingFaceDatasetLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA

from huggingface_hub import login

login(token='HF token')

dataset_name="ruslanmv/ai-medical-chatbot"

#create a loader instance
loader_doc= HuggingFaceDatasetLoader(dataset_name, "Doctor")
doctor_data=loader_doc.load()

##selecting the first 500 entries

doctor_data=doctor_data[:500]
doctor_data[:2]

doctor_data

#load the embedding model from Huggingface
#enable GPU acceleration
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={
        "device": "cuda"  # 👈 enables GPU
    },

    #this is the embedding model which only converts text->vectors for storage in the vector db
    encode_kwargs={
        "batch_size": 64,       # faster on GPU
        "normalize_embeddings": True
    }
)

"""#RAG pipeline

User Question-> Embedding Model->FAISS similarity search->Relevant Documents->LLM (chat model)->Final Answer
"""

#sample text to check the embeddings
text="Hello doctor, I am feeling a little dizzy"
query_res=embeddings.embed_query(text)
query_res[:5]

#from google.colab import drive
drive.mount('/content/drive')

#convert the data into embeddings
#save them into the vector db
#perform similarity search using FAISS
from langchain_community.vectorstores import FAISS
vector_db=FAISS.from_documents(doctor_data, embeddings)
vector_db.save_local("/content/drive/MyDrive/faiss_doctor_index")

question="hello doctor, I have a headache"
searchDocs=vector_db.similarity_search(question)

print(searchDocs[0].page_content)

#converting the vector db into a retriever

retriever=vector_db.as_retriever()

retriever

from huggingface_hub import login
login()

#using mistral 7B instruct as the LLM(chat model) since it is non gated

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM,pipeline

base_model=base_model = "mistralai/Mistral-7B-Instruct-v0.2"
#loaded directly from HF

tokenizer = AutoTokenizer.from_pretrained(base_model)

#model
model = AutoModelForCausalLM.from_pretrained(
        base_model,
        return_dict=True,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
)
#pipeline for txt generation
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=120
)
llm = HuggingFacePipeline(pipeline=pipe)

#creating a question answer chain

#from langchain import hub

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

retriver=vector_db.as_retriever()




rag_prompt=ChatPromptTemplate.from_template(   """Answer the question based only on the context below:

{context}

Question: {question}
"""
)
#prompt template for the LLM

qa_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | rag_prompt
    | llm
    | StrOutputParser()
)

#testing with questions

question="hello doctor, I have a stomach ache, the upper abdomen hurts"
result=qa_chain.invoke(question)
print(result)

question="hello doctor, the right hand's palm of my hand is swollen what do I do know?"
result=qa_chain.invoke(question)
print(result)

